forum_modules/exporter/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import state, running, download

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('state/')),  state, name='exporter_state'),
    url(r'^%s(?P<mode>\w+)/%s$' % (_('admin/'), _('running/')),  running, name='exporter_running'),
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('download/')),  download, name='exporter_download'),
)

forum_modules/robotstxt/urls.py
from django.conf.urls.defaults import *
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value)),
)

forum_modules/updates/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import updater_index, updater_check

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('updater/'), _('check/')),  updater_check, name='updater_check'),
)

urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'', include('forum.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns = patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    ) + urlpatterns

handler404 = 'forum.views.meta.page'
handler500 = 'forum.views.meta.error_handler'

forum/models/meta.py
from django.utils.translation import ugettext as _
from base import *

class Vote(models.Model):
    user = models.ForeignKey(User, related_name="votes")
    node = models.ForeignKey(Node, related_name="votes")
    value = models.SmallIntegerField()
    action = models.OneToOneField(Action, related_name="vote")
    voted_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Flag(models.Model):
    user = models.ForeignKey(User, related_name="flags")
    node = models.ForeignKey(Node, related_name="flags")
    reason = models.CharField(max_length=300)
    action = models.OneToOneField(Action, related_name="flag")
    flagged_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Badge(BaseModel):
    GOLD = 1
    SILVER = 2
    BRONZE = 3

    type        = models.SmallIntegerField()
    cls         = models.CharField(max_length=50, null=True)
    awarded_count = models.PositiveIntegerField(default=0)
    
    awarded_to    = models.ManyToManyField(User, through='Award', related_name='badges')

    def get_handler(self):
        from forum.badges import BadgesMeta
        return BadgesMeta.by_id.get(self.id, None)

    @property
    def name(self):
        cls = self.get_handler()
        return cls and cls.name or _("Unknown")

    @property
    def description(self):
        cls = self.get_handler()
        return cls and cls.description or _("No description available")

    @models.permalink
    def get_absolute_url(self):
        return ('badge', [], {'id': self.id, 'slug': slugify(self.name)})

    def save(self, *args, **kwargs):
        if isinstance(self.awarded_count, models.expressions.ExpressionNode):
            super(Badge, self).save(*args, **kwargs)
            self.awarded_count = self.__class__.objects.filter(id=self.id).values_list('awarded_count', flat=True)[0]
        else:
            super(Badge, self).save(*args, **kwargs)


    class Meta:
        app_label = 'forum'


class Award(models.Model):
    user = models.ForeignKey(User)
    badge = models.ForeignKey('Badge', related_name="awards")
    node = models.ForeignKey(Node, null=True)

    awarded_at = models.DateTimeField(default=datetime.datetime.now)

    trigger = models.ForeignKey(Action, related_name="awards", null=True)
    action = models.OneToOneField(Action, related_name="award")


    class Meta:
        unique_together = ('user', 'badge', 'node')
        app_label = 'forum'

forum/models/node.py
from base import *
import re
from tag import Tag

import markdown
from django.utils.translation import ugettext as _
from django.utils.safestring import mark_safe
from django.utils.html import strip_tags
from forum.utils.html import sanitize_html
from forum.utils.userlinking import auto_user_link
from forum.settings import SUMMARY_LENGTH
from utils import PickledObjectField

class NodeContent(models.Model):
    title      = models.CharField(max_length=300)
    tagnames   = models.CharField(max_length=125)
    author     = models.ForeignKey(User, related_name='%(class)ss')
    body       = models.TextField()

    @property
    def user(self):
        return self.author

    @property
    def html(self):
        return self.body

    def rendered(self, content):
        return auto_user_link(self, self._as_markdown(content, *['auto_linker']))

    @classmethod
    def _as_markdown(cls, content, *extensions):
        try:
            return mark_safe(sanitize_html(markdown.markdown(content, extensions=extensions)))
        except Exception, e:
            import traceback
            logging.error("Caught exception %s in markdown parser rendering %s %s:\s %s" % (
                str(e), cls.__name__, str(e), traceback.format_exc()))
            return ''

    def as_markdown(self, *extensions):
        return self._as_markdown(self.body, *extensions)

    @property
    def headline(self):
        title = self.title

        # Replaces multiple spaces with single ones.
        title = re.sub(' +',' ', title)

        return title

    def tagname_list(self):
        if self.tagnames:
            return [name.strip() for name in self.tagnames.split() if name]
        else:
            return []

    def tagname_meta_generator(self):
        return u','.join([tag for tag in self.tagname_list()])

    class Meta:
        abstract = True
        app_label = 'forum'

class NodeMetaClass(BaseMetaClass):
    types = {}

    def __new__(cls, *args, **kwargs):
        new_cls = super(NodeMetaClass, cls).__new__(cls, *args, **kwargs)

        if not new_cls._meta.abstract and new_cls.__name__ is not 'Node':
            NodeMetaClass.types[new_cls.get_type()] = new_cls

        return new_cls

    @classmethod
    def setup_relations(cls):
        for node_cls in NodeMetaClass.types.values():
            NodeMetaClass.setup_relation(node_cls)

    @classmethod
    def setup_relation(cls, node_cls):
        name = node_cls.__name__.lower()

        def children(self):
            return node_cls.objects.filter(parent=self)

        def parent(self):
            if (self.parent is not None) and self.parent.node_type == name:
                return self.parent.leaf

            return None

        Node.add_to_class(name + 's', property(children))
        Node.add_to_class(name, property(parent))


class NodeQuerySet(CachedQuerySet):
    def obj_from_datadict(self, datadict):
        cls = NodeMetaClass.types.get(datadict.get("node_type", ""), None)
        if cls:
            obj = cls()
            obj.__dict__.update(datadict)
            return obj
        else:
            return super(NodeQuerySet, self).obj_from_datadict(datadict)

    def get(self, *args, **kwargs):
        node = super(NodeQuerySet, self).get(*args, **kwargs).leaf

        if not isinstance(node, self.model):
            raise self.model.DoesNotExist()

        return node

    def any_state(self, *args):
        filter = None

        for s in args:
            s_filter = models.Q(state_string__contains="(%s)" % s)
            filter = filter and (filter | s_filter) or s_filter

        if filter:
            return self.filter(filter)
        else:
            return self

    def all_states(self, *args):
        filter = None

        for s in args:
            s_filter = models.Q(state_string__contains="(%s)" % s)
            filter = filter and (filter & s_filter) or s_filter

        if filter:
            return self.filter(filter)
        else:
            return self

    def filter_state(self, **kwargs):
        apply_bool = lambda q, b: b and q or ~q
        return self.filter(*[apply_bool(models.Q(state_string__contains="(%s)" % s), b) for s, b in kwargs.items()])

    def children_count(self, child_type):
        return NodeMetaClass.types[child_type].objects.filter_state(deleted=False).filter(parent__in=self).count()


class NodeManager(CachedManager):
    use_for_related_fields = True

    def get_query_set(self):
        qs = NodeQuerySet(self.model)

        # If the node is an answer, question or comment we filter the Node model by type
        if self.model is not Node:
            qs = qs.filter(node_type=self.model.get_type())

        return qs

    def get_for_types(self, types, *args, **kwargs):
        kwargs['node_type__in'] = [t.get_type() for t in types]
        return self.get(*args, **kwargs)

    def filter_state(self, **kwargs):
        return self.all().filter_state(**kwargs)


class NodeStateDict(object):
    def __init__(self, node):
        self.__dict__['_node'] = node

    def __getattr__(self, name):
        if self.__dict__.get(name, None):
            return self.__dict__[name]

        try:
            node = self.__dict__['_node']
            action = NodeState.objects.get(node=node, state_type=name).action
            self.__dict__[name] = action
            return action
        except:
            return None

    def __setattr__(self, name, value):
        current = self.__getattr__(name)

        if value:
            if current:
                current.action = value
                current.save()
            else:
                node = self.__dict__['_node']
                state = NodeState(node=node, action=value, state_type=name)
                state.save()
                self.__dict__[name] = value

                if not "(%s)" % name in node.state_string:
                    node.state_string = "%s(%s)" % (node.state_string, name)
                    node.save()
        else:
            if current:
                node = self.__dict__['_node']
                node.state_string = "".join("(%s)" % s for s in re.findall('\w+', node.state_string) if s != name)
                node.save()
                current.node_state.delete()
                del self.__dict__[name]


class NodeStateQuery(object):
    def __init__(self, node):
        self.__dict__['_node'] = node

    def __getattr__(self, name):
        node = self.__dict__['_node']
        return "(%s)" % name in node.state_string


class Node(BaseModel, NodeContent):
    __metaclass__ = NodeMetaClass

    node_type            = models.CharField(max_length=16, default='node')
    parent               = models.ForeignKey('Node', related_name='children', null=True)
    abs_parent           = models.ForeignKey('Node', related_name='all_children', null=True)

    added_at             = models.DateTimeField(default=datetime.datetime.now)
    score                 = models.IntegerField(default=0)

    state_string          = models.TextField(default='')
    last_edited           = models.ForeignKey('Action', null=True, unique=True, related_name="edited_node")

    last_activity_by       = models.ForeignKey(User, null=True)
    last_activity_at       = models.DateTimeField(null=True, blank=True)

    tags                 = models.ManyToManyField('Tag', related_name='%(class)ss')
    active_revision       = models.OneToOneField('NodeRevision', related_name='active', null=True)

    extra = PickledObjectField()
    extra_ref = models.ForeignKey('Node', null=True)
    extra_count = models.IntegerField(default=0)

    marked = models.BooleanField(default=False)

    comment_count = DenormalizedField("children", node_type="comment", canceled=False)
    flag_count = DenormalizedField("flags")

    friendly_name = _("post")

    objects = NodeManager()

    def __unicode__(self):
        return self.headline

    @classmethod
    def _generate_cache_key(cls, key, group="node"):
        return super(Node, cls)._generate_cache_key(key, group)
        
    @classmethod
    def get_type(cls):
        return cls.__name__.lower()

    @property
    def leaf(self):
        leaf_cls = NodeMetaClass.types.get(self.node_type, None)

        if leaf_cls is None:
            return self

        leaf = leaf_cls()
        leaf.__dict__ = self.__dict__
        return leaf

    @property
    def nstate(self):
        state = self.__dict__.get('_nstate', None)

        if state is None:
            state = NodeStateDict(self)
            self._nstate = state

        return state

    @property
    def nis(self):
        nis = self.__dict__.get('_nis', None)

        if nis is None:
            nis = NodeStateQuery(self)
            self._nis = nis

        return nis

    @property
    def last_activity(self):
        try:
            return self.actions.order_by('-action_date')[0].action_date
        except:
            return self.last_seen

    @property
    def state_list(self):
        return [s.state_type for s in self.states.all()]

    @property
    def deleted(self):
        return self.nis.deleted

    @property
    def absolute_parent(self):
        if not self.abs_parent_id:
            return self

        return self.abs_parent

    @property
    def summary(self):
        content = strip_tags(self.html)[:SUMMARY_LENGTH]

        # Remove multiple spaces.
        content = re.sub(' +',' ', content)

        # Remove line breaks. We don't need them at all.
        content = content.replace("\n", '')

        return content

    @models.permalink
    def get_revisions_url(self):
        return ('revisions', (), {'id': self.id})

    def update_last_activity(self, user, save=False, time=None):
        if not time:
            time = datetime.datetime.now()

        self.last_activity_by = user
        self.last_activity_at = time

        if self.parent:
            self.parent.update_last_activity(user, save=True, time=time)

        if save:

forum/models/question.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

class QuestionManager(NodeManager):
    def search(self, keywords):
        return False, self.filter(models.Q(title__icontains=keywords) | models.Q(body__icontains=keywords))

class Question(Node):
    class Meta(Node.Meta):
        proxy = True

    answer_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer")
    accepted_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer", marked=True)
    favorite_count = DenormalizedField("actions", action_type="favorite", canceled=False)

    friendly_name = _("question")
    objects = QuestionManager()

    @property
    def closed(self):
        return self.nis.closed

    @property    
    def view_count(self):
        return self.extra_count

    @property
    def headline(self):
        if self.nis.deleted:
            return _('[deleted] ') + self.title

        if self.nis.closed:
            return _('[closed] ') + self.title

        return self.title

    @property
    def accepted_answers(self):
        return self.answers.filter(~models.Q(state_string__contains="(deleted)"), marked=True)

    @models.permalink    
    def get_absolute_url(self):
        return ('question', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})
        
    def meta_description(self):
        return self.summary

    def get_revision_url(self):
        return reverse('question_revisions', args=[self.id])

    def get_related_questions(self, count=10):
        cache_key = '%s.related_questions:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Question.objects.filter_state(deleted=False).values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Question.objects.get(id=r['id']) for r in related_list]
    



class QuestionSubscription(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Node)
    auto_subscription = models.BooleanField(default=True)
    last_view = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        app_label = 'forum'


class QuestionRevision(NodeRevision):
    class Meta:
        proxy = True
        

forum/skins/fresh/templates/answer_edit_tips.html
<!-- template answer_edit_tips.html -->
{% load i18n general_sidebar_tags %}
<div class="boxC">
    <p class="subtitle darkred">{% trans "answer tips" %}</p>
    <div>
        <ul class="list-item">
            <li> <b>{% trans "please make your answer relevant to this community" %}</b>
            </li>
            <li>
                {% trans  "try to give an answer, rather than engage into a discussion" %}
            </li>
            <li>
                {% trans "please try to provide details" %}
            </li>
            <li>
				{% trans "be clear and concise" %}
            </li>
        </ul>
        <p class='info-box-follow-up-links'>
            <a href="{% url faq %}" target="_blank" title="{% trans "see frequently posted papers" %}">faq &raquo;</a>
        </p>
    </div>
</div>

{% markdown_help %}
<!-- end template answer_edit_tips.html -->

forum/skins/fresh/templates/badge.html
{% extends "base_content.html" %}
<!-- template badge.html -->
{% load i18n %}
{% load extra_tags %}
{% load user_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{{ badge.name }} - {% trans "Badge" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $("#nav_badges").attr('className',"on");
        });
         
        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Badge" %}
</div>
<div id="main-body" style="width:100%;margin-bottom:20px">
    <p>
        <a href="{{badge.get_absolute_url}}" title="{{ badge.get_type_display }} : {{ badge.description }}" class="medal"><span class="badge{{ badge.type }}">&#9679;</span>&nbsp;{{ badge.name }}</a> {{ badge.description }}
    </p>
    <div>
        {% if badge.awarded_count %}
        <p style="float:left"><span class="count">{{ award_count|intcomma }}</span>
        <strong>{% trans "The users have been awarded with badges:" %}</strong></p>
        {% endif %}
    </div>
    <div id="award-list" style="clear:both;margin-left:20px;line-height:25px;">
        {% for award in awards %}
        <p style="width:220px;float:left">{% user_signature award.user "badges" %}<span class="tag-number"> &#215; {{ award.count|intcomma }}</span></p>
        {% endfor %}
    </div>

</div>
{% endblock %}
<!-- end template badge.html -->

forum/skins/fresh/templates/badges.html
{% extends "base.html" %}
<!-- template badges.html -->
{% load extra_tags %}
{% load humanize %}
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Badges summary" %}{% endspaceless %}{% endblock %}
{% block content %}
<div class="headlineA">
        <span class="headMedals">{% trans "Badges" %}</span>
</div>
<div class="badges" id="main-body" style="width:100%">
    <p>
	{% trans "Community gives you awards for your papers, responses and votes." %}
	{% blocktrans %}Below is the list of available badges and number of times each type of badge has been awarded.
    {% endblocktrans %}
    </p>
    <div id="medalList">
        {% for badge in badges %}
        <div style="clear:both;line-height:30px">
            <div style="float:left;min-width:30px;text-align:right;height:30px">
            {% if badge.id in mybadges %}
                 <span style="font-size:175%; padding-right:5px; color:#5B9058;">&#10004;</span>
            {% endif %}
            </div>
            <div style="float:left;width:230px;">
                <a href="{{badge.get_absolute_url}}" title="{{ badge.get_type_display }} : {{ badge.description }}" class="medal"><span class="badge{{ badge.type }}">&#9679;</span>&nbsp;{{ badge.name }}</a><strong> &#215; {{ badge.awarded_count|intcomma }}</strong>
            </div>
            <p style="float:left;margin-top:8px;">
                {{ badge.description }}
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block sidebar %}

<div class="boxC">
    <h3>{% trans "Community badges" %}</h3>
    <div class="body">
    <p>
        <span title="{% trans "gold badge: the highest honor and is very rare" %}" class="medal"><span class="badge1">&#9679;</span>&nbsp;{% trans "gold" %}</span>
    </p>
    <p>
	{% trans "gold badge description" %}
    </p>
    <p>
        <span
			title="{% trans "silver badge: occasionally awarded for the very high quality contributions" %}" 
			class="medal"><span class="badge2">&#9679;</span>&nbsp;{% trans "silver" %}</span>
    </p>
    <p>
	{% trans "silver badge description" %}
    </p>
    <p>
        <span title="{% trans "bronze badge: often given as a special honor" %}" class="medal">
		<span class="badge3">&#9679;</span>&nbsp;{% trans "bronze" %}</span>
    </p>
    <p>
	{% trans "bronze badge description" %}
    </p>
    </div>
</div>
{% endblock %}
<!-- end template badges.html -->

forum/skins/fresh/templates/email_base.html
{% load extra_filters %}
{% load extra_tags %}
{% load email_tags %}
{% load i18n %}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <style type="text/css">
            body {
                background: #FFF;
                font-size: 12px;
                line-height: 150%;
                margin: 0;
                padding: 0;
                color: #000;
                font-family: sans-serif;
            }

            #wrapper {
                width: 600px;
                margin: auto;
                padding: 0;
            }

            a img {
                border: none;
            }
        </style>
    </head>
    <body>
        <a href="{% fullurl index %}">
            <img src="cid:logo" title="{% trans "home" %}" alt="{{settings.APP_TITLE}} logo"/>
        </a>
        <br />
        <p>{{ settings.APP_TITLE }}</p>
    <br /><br />
    <div id="wrapper">
            <div id="room">
                <div id="CALeft">
                    {% block content%}
                    {% endblock%}
                </div>
            </div>
            <div class="spacer3"></div>
        </div>
    </body>
</html>

forum/skins/fresh/templates/notarobot.html
{% extends "base_content.html" %}
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Please prove that you are a Human Being" %}{% endspaceless %}{% endblock %}
{% block content %}
{% comment %} this form is set up to be used in wizards {% endcomment %}
<form name="notarobot" action="." method="POST">
    {% csrf_token %}
    <div>
    {{form}}
    </div>
    <input type="submit" value="{% trans "I am a Human Being" %}" class="submit" style="float:left"/>
    <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
    {{ previous_fields|safe }}
    </form>
</form>
{% endblock %}

forum/skins/fresh/templates/opensearch.html
{% load i18n %}
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
   <ShortName>{{ settings.APP_SHORT_NAME }} {% trans "Search" %}</ShortName>
   <Description>{% trans "Search" %} {{ settings.APP_SHORT_NAME }} {% trans "using your browser." %}</Description>
   <Tags>{{ settings.APP_KEYWORDS }}</Tags>
   <Url type="text/html" template="{{ settings.APP_URL }}/{% trans "search" %}/?q={searchTerms}&amp;t=question"/>
</OpenSearchDescription>

forum/skins/fresh/templates/pagesize.html
<!-- template pagesize.html -->
{% spaceless %}
{% load i18n %}
{% if is_paginated %}
<div class="paginator">
    <span class="text">{% trans "posts per page" %}</span>
    {% ifequal pagesize 10 %}
        <span class="curr">10</span>
    {% else %}
        <span class="page"><a href="{{base_url}}pagesize=10">10</a></span>
    {% endifequal %}
    
    {% ifequal pagesize 30 %}
        <span class="curr">30</span>
    {% else %}
        <span class="page"><a href="{{base_url}}pagesize=30">30</a></span>
    {% endifequal %}
    
    {% ifequal pagesize 50 %}
        <span class="curr">50</span>
    {% else %}
        <span class="page"><a href="{{base_url}}pagesize=50">50</a></span>
    {% endifequal %}
</div> 
{% endif %}
{% endspaceless %}
<!-- end template pagesize.html -->

forum/skins/fresh/templates/question_retag.html
{% extends "base.html" %}
<!-- question_retag.html -->
{% load extra_tags %}
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Change tags" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type="text/javascript">
        
        $().ready(function(){
            $("#id_tags").autocomplete("{% url matching_tags %}", {
        		matchContains: true,
                max: 20,
                multiple: true,
                multipleSeparator: " ",
                highlightItem: true,
                scroll: true,
                scrollHeight: 300,
        		/*formatItem: function(row, i, max) {
        			return row.n + " ("+ row.c +")";
        		},
                formatResult: function(row, i, max){
                    return row.n;
                }*/
                formatItem: function(row, i, max, value) {
                    return row[1] + " (" + row[2] + ")";
                },

                formatResult: function(row, i, max, value){
                    return row[1];
                }
                
            });

        });
        </script>
{% endblock %}
        
{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Change tags" %} [<a href="{{ question.get_absolute_url }}">{% trans "back" %}</a>]
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmretag" action="{% url edit_question question.id %}" method="post">
            {% csrf_token %}
            <h3>
                {{ question.headline }}
            </h3>
            <div id="description" class="edit-content-html">
                {{ question.html|safe }}
            </div>
           
            
            <div class="form-item">
                <strong>{{ form.tags.label_tag }}:</strong> <span class="form-error"></span><br/>
                {{ form.tags }}  {{ form.tags.errors }}
                <div class="title-desc">
                    {{ form.tags.help_text }}
                </div>
            </div>
            <div class="error" ></div>
            <input type="submit" value="{% trans "Save edit" %}" class="submit" />
            <input type="button" value="{% trans "Cancel" %}" class="submit" onclick="history.back(-1);" />
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}
<div class="boxC">
    <p class="subtitle">{% trans "Why use and modify tags?" %}</p>
    <ul class="list-item">
        <li>
            {% trans "tags help us keep papers organized" %}
        </li>
        <li>
            {% trans "tag editors receive special awards from the community" %}
        </li>
    </ul>
    <p class='info-box-follow-up-links'>
        <a href="{% url faq %}">faq &raquo;</a>
    </p>
</div>

{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end question_retag.html -->

forum/skins/fresh/templates/question_summary_list_roll.html
    <div class="qstA">
        <h2>
            <a href="{{ question.get_absolute_url }}">{{ question.headline }}</a>
        </h2>
        <div class="stat">
            <table>
                <tr>
                    <td><span class="num">{{ question.answer_count|intcomma }}</span> </td>
                    <td><span class="num">{{ question.score|intcomma }}</span> </td>
                    <td><span class="num">{{ question.view_count|decorated_int|safe }}</span> </td>
                </tr>  
                <tr>
                    <td><span class="unit">{% trans "answers" %}</span></td>
                    <td><span class="unit">{% trans "votes" %}</span></td>
                    <td><span class="unit">{% trans "views" %}</span></td>
                </tr> 
            </table>
        </div>
        
        <div class="summary">
            {{ question.summary }}...                
        </div>
        
        {% ifequal tab_id 'active'%}
        {% if question.wiki and settings.WIKI_ON %}
        <span class="from wiki">{% trans "community wiki" %}</span>
        <span class="date" title="{{ question.added_at }}">{% diff_date question.added_at %}</span>
        {% else %}
        <div class="from">
            {% comment %}{% gravatar question.last_activity_by 24 %}{% endcomment %}
            <span class="author"><a href="{{ question.last_activity_by.get_profile_url }}">{{ question.last_activity_by }}</a></span>
            <span class="score">{% get_score_badge question.last_activity_by %} </span>
            <span class="date" title="{{ question.last_activity_at }}">{% diff_date question.last_activity_at %}</span>
        </div>
        {% endif %}
        {% else %}
        {% if question.wiki and settings.WIKI_ON %}
        <span class="from wiki">{% trans "community wiki" %}</span>
        <span class="date" title="{{ question.added_at }}">{% diff_date question.added_at %}</span>
        {% else %}
        <div class="from">
            {% comment %}{% gravatar question.author 24 %}{% endcomment %}
            <span class="author"><a href="{{ question.author.get_profile_url }}">{{ question.author }}</a></span>
            <span class="score">{% get_score_badge question.author %} </span>
            <span class="date" title="{{ question.added_at }}">{% diff_date question.added_at %}</span>
        </div>
        {% endif %}
        {% endifequal %}
        
        <div class="tags">
        {% for tag in question.tagname_list %}
        <a class="tag-link-{{ tag }}" href="{% url tag_questions tag|urlencode %}" title="{% trans "see papers tagged" %}'{{ tag }}'{% trans "using tags" %}" rel="tag">{{ tag }}</a>
        {% endfor %}
        </div>
    </div>